Update: signup fields
mugna-tech/django-template pull request #181
Opened 2024-10-09 07:38 UTC by rzykie

## Ticket - [#7](https://github.com/orgs/mugna-tech/projects/30?pane=issue&itemId=81694335&issue=mugna-tech%7Creact-blueprint%7C7)

_Related tickets:_  
_Related PRs:

## Type of PR

- [ ] New Feature
- [x] Bug Fix
- [x] Minor Change

## Changes introduced

- Add django-phonenumber-field and phonenumbers packages
- Add register serializer in settings
- Update rest auth config in settings
- Update user model to include phone number field
- Add custom register serializer
- Add migration file for user model
- Add test for custom register serializer

2024-10-09 07:49 UTC, jacelo requested changes

2024-10-09 07:49 UTC, jacelo commented on {{cookiecutter.project_slug_dashed}}/users/api/v1/tests/test_serializers.py
> +            "username": "johnsmith",
@rzykie Question, since we have the option to login either via email or username, what happens to the username here if our auth is via email?

Also, based on the figma design, the signup form does not have a username. So the frontend won't be able to pass data for this. It would be better to setup you tests with a more realistic scenario.

2024-10-09 08:03 UTC, rzykie commented on {{cookiecutter.project_slug_dashed}}/users/api/v1/tests/test_serializers.py
> +            "username": "johnsmith",
ill adjust the test to catch these scenarios

2024-10-10 05:52 UTC, jacelo approved these changes
LGTM

2024-10-10 06:21 UTC, merged